---
name: Deploy lambda function 
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ZIP_FILE: 'app-${{ github.sha }}.zip'

    steps: 
      - name: Checkout
        uses: actions/checkout@v2
  
      - name: Configure AWS credentials
        id: aws-conf
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
  
      - name: Create zip
        id: lambda-zip
        run: |
          zip -r deploy.zip ./ --exclude *git*
  
      - name: Install dependency
        run: pip install boto3
  
      - name: Upload to Lambda
        run: aws lambda update-function-code --function-name  arn:aws:lambda:us-east-1:360833390362:function:PythonFunction --zip-file=fileb://deploy.zip
  
